---
apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec:
  externalIPs:
    - "172.19.32.212"
  ports:
    -
      name: tomcat-port
      port: 9082
      targetPort: 8080
  selector:
    app: auth
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        -
          image: tomcat:8
          name: tomcatcontainer
          ports:
            -
              containerPort: 8080

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: tomcat
spec:
  maxReplicas: 5
  metrics:
    -
      resource:
        name: cpu
        targetAverageUtilization: 50
      type: Resource
    -
      resource:
        name: memory
        targetAverageValue: 1000Mi
      type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: tomcat
